<?php

namespace AppBundle\Repository;

/**
 * AdvertsPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertsPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
