<?php

namespace AppBundle\Repository;

/**
 * AdvertsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertsGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
