<?php

namespace AppBundle\Repository;

/**
 * AdvertsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertsRepository extends \Doctrine\ORM\EntityRepository
{
}
