<?php

namespace AppBundle\Repository;

/**
 * AdvertsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
